import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Bed, Clock3, DoorOpen, UserCheck, Users } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { Filters, MetricCard, StatusBadge } from "@/components/dashboard-ui";

export const Route = createFileRoute("/agenda")({ head: () => ({ meta: [{ title: "Agenda Cirúrgica — Centro Cirúrgico Materno" }, { name: "description", content: "Agenda diária e capacidade do bloco cirúrgico materno." }, { property: "og:title", content: "Agenda Cirúrgica — Centro Cirúrgico Materno" }, { property: "og:description", content: "Agenda diária e capacidade do bloco cirúrgico materno." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Agenda });
const rows = [
  ["09:00", "Sala 01", "Cesárea", "Eletiva", "Em cirurgia", "01h30", "Estimar saída 10:55"], ["09:30", "Sala 02", "Cesárea", "Urgência", "Em cirurgia", "01h15", "Acompanhar alerta"], ["10:30", "Sala 03", "Cerclagem", "Eletiva", "Em preparo", "00h50", "Resolver pendência"], ["10:00", "Sala 06", "Cesárea", "Eletiva", "Em atraso", "01h30", "Paciente em preparo"], ["11:10", "Sala 05", "Cesárea", "Eletiva", "Livre", "01h20", "Confirmar equipe"], ["12:20", "Sala 04", "Revisão uterina", "Urgência", "Livre", "00h55", "Aguardar liberação"], ["13:30", "Sala 01", "Cesárea", "Eletiva", "Livre", "01h20", "Chamar paciente"],
];
function Agenda() { const [filter, setFilter] = useState("Dia inteiro"); return <div><PageHeader title="Agenda Cirúrgica" subtitle="Terça-feira, 22 de setembro de 2026" /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Próxima sala disponível" value="Sala 04 · 10:47" icon={DoorOpen} /><MetricCard label="Risco de sobreposição" value="2 salas" icon={Clock3} tone="warn" /><MetricCard label="Aptas para chamada" value={2} icon={UserCheck} tone="good" /><MetricCard label="Com pendências" value={1} icon={Users} tone="warn" /><MetricCard label="Vagas na RPA" value="3 de 6" icon={Bed} /></section><div className="my-6 flex flex-wrap items-center justify-between gap-3"><Filters options={["Dia inteiro", "Manhã", "Tarde"]} active={filter} onChange={setFilter} /><div className="flex gap-2"><select aria-label="Filtrar sala" className="select-field"><option>Todas as salas</option><option>Sala 01</option><option>Sala 02</option></select><select aria-label="Filtrar prioridade" className="select-field"><option>Todas as prioridades</option><option>Eletiva</option><option>Urgência</option></select></div></div><div className="overflow-hidden rounded-md border border-border bg-card shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr>{["Horário", "Sala", "Procedimento", "Prioridade", "Situação", "Duração", "Próxima ação"].map((h) => <th key={h} className="px-4 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-t border-border hover:bg-muted/40">{row.map((cell, j) => <td key={j} className="px-4 py-4 font-medium">{j === 4 ? <StatusBadge status={cell} /> : <span className={j === 3 && cell === "Urgência" ? "font-bold text-critical" : j === 0 || j === 5 ? "font-mono tabular-nums" : ""}>{cell}</span>}</td>)}</tr>)}</tbody></table></div></div></div>; }