import { createFileRoute } from "@tanstack/react-router";
import { Activity, Bell, CalendarCheck, Clock3, DoorOpen, RotateCcw, TrendingUp, XCircle } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/app-shell";
import { MetricCard } from "@/components/dashboard-ui";

export const Route = createFileRoute("/indicadores")({ head: () => ({ meta: [{ title: "Indicadores — Centro Cirúrgico Materno" }, { name: "description", content: "Indicadores de desempenho e utilização do centro cirúrgico materno." }, { property: "og:title", content: "Indicadores — Centro Cirúrgico Materno" }, { property: "og:description", content: "Indicadores de desempenho e utilização do centro cirúrgico materno." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Indicadores });
const roomTime = [{ name: "Sala 01", minutos: 78 }, { name: "Sala 02", minutos: 86 }, { name: "Sala 03", minutos: 52 }, { name: "Sala 04", minutos: 71 }, { name: "Sala 05", minutos: 68 }, { name: "Sala 06", minutos: 81 }];
const delays = [{ name: "Preparo", valor: 4 }, { name: "Equipe", valor: 2 }, { name: "Leito", valor: 2 }, { name: "Exames", valor: 1 }];
const trend = [{ hora: "07h", ocupacao: 33 }, { hora: "08h", ocupacao: 50 }, { hora: "09h", ocupacao: 67 }, { hora: "10h", ocupacao: 83 }, { hora: "11h", ocupacao: 67 }, { hora: "12h", ocupacao: 75 }];
function IndicatorsChart({ type, data, dataKey }: { type: "bar" | "line"; data: { name?: string; hora?: string; [key: string]: string | number | undefined }[]; dataKey: string }) { return <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%">{type === "bar" ? <BarChart data={data} margin={{ top: 10, right: 10, bottom: 5, left: -20 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" /><XAxis dataKey="name" tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey={dataKey} fill="var(--primary)" radius={[3,3,0,0]} /></BarChart> : <LineChart data={data} margin={{ top: 10, right: 10, bottom: 5, left: -20 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" /><XAxis dataKey="hora" tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: "var(--muted-foreground)" }} axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey={dataKey} stroke="var(--success)" strokeWidth={3} dot={{ fill: "var(--success)", r: 4 }} /></LineChart>}</ResponsiveContainer></div>; }
function Indicadores() { return <div><PageHeader title="Indicadores do Dia" subtitle="Desempenho operacional · 22 de setembro de 2026" /><section className="grid grid-cols-2 gap-3 md:grid-cols-4"><MetricCard label="Programados" value={12} icon={CalendarCheck} /><MetricCard label="Concluídos" value={5} icon={Activity} tone="good" /><MetricCard label="Início no horário" value="60%" icon={TrendingUp} /><MetricCard label="Tempo médio cirurgia" value="01h18" icon={Clock3} /><MetricCard label="Giro médio de sala" value="00h34" icon={RotateCcw} /><MetricCard label="Taxa de ocupação" value="83%" icon={DoorOpen} tone="good" /><MetricCard label="Reagendamentos" value={1} icon={XCircle} /><MetricCard label="Alertas em aberto" value={5} icon={Bell} tone="warn" /></section><section className="mt-6 grid gap-4 xl:grid-cols-2"><ChartCard title="Tempo médio por sala" subtitle="Duração em minutos"><IndicatorsChart type="bar" data={roomTime} dataKey="minutos" /></ChartCard><ChartCard title="Ocupação ao longo do turno" subtitle="Percentual de salas em uso"><IndicatorsChart type="line" data={trend} dataKey="ocupacao" /></ChartCard><ChartCard title="Principais motivos de atraso" subtitle="Ocorrências registradas"><IndicatorsChart type="bar" data={delays} dataKey="valor" /></ChartCard><div className="rounded-md border border-border bg-card p-5 shadow-card"><h2 className="font-bold">Status atual das salas</h2><p className="mt-1 text-xs text-muted-foreground">Distribuição operacional às 10:50</p><div className="mt-8 space-y-5">{[["Em cirurgia",3,"bg-success"],["Em preparo",1,"bg-caution"],["Em limpeza",1,"bg-cleaning"],["Livre",1,"bg-muted-foreground"]].map(([name,value,color]) => <div key={String(name)}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{name}</span><span className="font-mono font-bold">{value}/6</span></div><div className="h-2 rounded-full bg-muted"><div className={`h-full rounded-full ${color}`} style={{ width: `${Number(value) / 6 * 100}%` }} /></div></div>)}</div></div></section></div>; }
function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="rounded-md border border-border bg-card p-5 shadow-card"><h2 className="font-bold">{title}</h2><p className="mb-4 mt-1 text-xs text-muted-foreground">{subtitle}</p>{children}</div>; }