import { createFileRoute } from "@tanstack/react-router";
import { Bed, Clock3, HeartPulse } from "lucide-react";
import { PageHeader } from "@/components/app-shell";
import { MetricCard, StatusBadge } from "@/components/dashboard-ui";

export const Route = createFileRoute("/recuperacao")({ head: () => ({ meta: [{ title: "Recuperação Pós-Anestésica — Centro Cirúrgico Materno" }, { name: "description", content: "Ocupação e situação dos leitos de recuperação pós-anestésica." }, { property: "og:title", content: "Recuperação Pós-Anestésica — Centro Cirúrgico Materno" }, { property: "og:description", content: "Ocupação e situação dos leitos de recuperação pós-anestésica." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Recuperacao });
const beds = [
  { bed: "RPA 01", patient: "M. S. A.", origin: "Sala 01", enter: "10:47", stay: "00h03", state: "Monitorização ativa", dest: "Alojamento conjunto", occupied: true },
  { bed: "RPA 02", patient: "J. F. R.", origin: "Sala 04", enter: "10:20", stay: "00h30", state: "Apta — aguardando leito", dest: "Alojamento conjunto", occupied: true },
  { bed: "RPA 03", patient: "A. C. L.", origin: "Sala 02", enter: "10:36", stay: "00h14", state: "Dor a reavaliar", dest: "Unidade materna", occupied: true },
  ...[4,5,6].map((n) => ({ bed: `RPA 0${n}`, patient: "—", origin: "—", enter: "—", stay: "—", state: "Disponível", dest: "—", occupied: false })),
];
function Recuperacao() { return <div><div className="flex flex-wrap items-start justify-between gap-4"><PageHeader title="Recuperação Pós-Anestésica" subtitle="Capacidade, permanência e transferências da RPA" /><div className="w-full sm:w-auto"><MetricCard label="Ocupação geral" value="3 de 6 leitos" icon={Bed} tone="good" /></div></div><div className="mb-6 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full w-1/2 rounded-full bg-success" /></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{beds.map((b) => <article key={b.bed} className="rounded-md border border-border bg-card shadow-card"><div className="flex items-center justify-between border-b border-border p-4"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-md bg-muted"><Bed className="h-4 w-4" /></span><h2 className="font-bold">{b.bed}</h2></div><StatusBadge status={b.state} /></div><div className="grid grid-cols-2 gap-4 p-4 text-sm"><Field label="Paciente" value={b.patient} /><Field label="Sala de origem" value={b.origin} /><Field label="Entrada" value={b.enter} /><Field label="Permanência" value={b.stay} mono /><div className="col-span-2"><Field label="Destino previsto" value={b.dest} /></div></div>{b.occupied && <div className="flex items-center gap-2 border-t border-border px-4 py-3 text-xs text-muted-foreground"><HeartPulse className="h-4 w-4" />Última avaliação há 8 minutos <Clock3 className="ml-auto h-4 w-4" /></div>}</article>)}</section></div>; }
function Field({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 font-semibold ${mono ? "font-mono" : ""}`}>{value}</p></div>; }