/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaRouteImport } from './routes/pa'
import { Route as PainelPacientesRouteImport } from './routes/painel-pacientes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaRoute = PaRouteImport.update({
  id: '/pa',
  path: '/pa',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPacientesRoute = PainelPacientesRouteImport.update({
  id: '/painel-pacientes',
  path: '/painel-pacientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pa': typeof PaRoute
  '/painel-pacientes': typeof PainelPacientesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pa': typeof PaRoute
  '/painel-pacientes': typeof PainelPacientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pa': typeof PaRoute
  '/painel-pacientes': typeof PainelPacientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pa' | '/painel-pacientes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pa' | '/painel-pacientes'
  id: '__root__' | '/' | '/pa' | '/painel-pacientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaRoute: typeof PaRoute
  PainelPacientesRoute: typeof PainelPacientesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pa': {
      id: '/pa'
      path: '/pa'
      fullPath: '/pa'
      preLoaderRoute: typeof PaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-pacientes': {
      id: '/painel-pacientes'
      path: '/painel-pacientes'
      fullPath: '/painel-pacientes'
      preLoaderRoute: typeof PainelPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaRoute: PaRoute,
  PainelPacientesRoute: PainelPacientesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
