/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as RecuperacaoRouteImport } from './routes/recuperacao'
import { Route as TvRouteImport } from './routes/tv'
import { Route as SalasRoomIdRouteImport } from './routes/salas.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperacaoRoute = RecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasRoomIdRoute = SalasRoomIdRouteImport.update({
  id: '/salas/$roomId',
  path: '/salas/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/indicadores': typeof IndicadoresRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/tv': typeof TvRoute
  '/salas/$roomId': typeof SalasRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/indicadores': typeof IndicadoresRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/tv': typeof TvRoute
  '/salas/$roomId': typeof SalasRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/indicadores': typeof IndicadoresRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/tv': typeof TvRoute
  '/salas/$roomId': typeof SalasRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/indicadores'
    | '/recuperacao'
    | '/tv'
    | '/salas/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/indicadores'
    | '/recuperacao'
    | '/tv'
    | '/salas/$roomId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alertas'
    | '/indicadores'
    | '/recuperacao'
    | '/tv'
    | '/salas/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlertasRoute: typeof AlertasRoute
  IndicadoresRoute: typeof IndicadoresRoute
  RecuperacaoRoute: typeof RecuperacaoRoute
  TvRoute: typeof TvRoute
  SalasRoomIdRoute: typeof SalasRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperacao': {
      id: '/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof RecuperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas/$roomId': {
      id: '/salas/$roomId'
      path: '/salas/$roomId'
      fullPath: '/salas/$roomId'
      preLoaderRoute: typeof SalasRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlertasRoute: AlertasRoute,
  IndicadoresRoute: IndicadoresRoute,
  RecuperacaoRoute: RecuperacaoRoute,
  TvRoute: TvRoute,
  SalasRoomIdRoute: SalasRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
